id: A4447257D
title: Heart of Vajrasattva—The Heart of Confession, the King of Purification Practices,
  from 'The Immaculate Secret Vajrasattva'
type: translation
pechas:
- IAEAB9BAB
- I20182EE9
- IA6EDCC3A
- I9AACBDA9
- I3EE4373F
- I0AC7BBB0
- I10B280B1
- I91B99452
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - nl
  - zh
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:39:50.195989
  last_modified_at: 2023-01-04 11:39:50.195999
  collections:
  - Do Khyentse Yeshe Dorje Series
  - Works of Tibetan Masters
alignment_to_base:
  IAEAB9BAB/62C6: 4DAA
  I20182EE9/B5AD: 4DAA
  IA6EDCC3A/714A: 4DAA
  I9AACBDA9/1F90: 4DAA
  I3EE4373F/FD50: 4DAA
  I0AC7BBB0/E9C4: 4DAA
  I10B280B1/71AF: 4DAA
  I91B99452/466C: 4DAA
